version: "3.9"

services:
  client:
    build:
      context: ./
    ports:
      - "5173:5173"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules